ecommerce/urls.py
from django.urls import path
from . import views

app_name = 'ecommerce'

urlpatterns = [
    path('', views.allproducts, name='allproducts'),
    path('productdetail/<int:pk>/', views.productdetail, name='productdetail'),
    path('pay/<int:pk>/', views.pay, name='pay'),
    path('confirm/<int:pk>',views.confirm, name='confirm'),
]

frauddetectionproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('paymentsystem/', include('paymentsystem.urls', namespace='paymentsystem')),
    path('ecommerce/', include('ecommerce.urls', namespace='ecommerce')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=500, default='')
    price = models.DecimalField(max_digits=10, decimal_places=2, default='')
    description = models.TextField(default='')
    image1 = models.ImageField(upload_to='images', default='')
    image2 = models.ImageField(upload_to='images', default='')
    image3 = models.ImageField(upload_to='images', default='')
    image4 = models.ImageField(upload_to='images', default='')

    def __str__(self):
        return self.name

ecommerce/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from paymentsystem.models import UserDetail
from django.contrib import messages

# Create your views here.
def allproducts(request):
    products = Product.objects.all()
    context = {
        'products' : products,
    }
    return render(request, 'ecommerce/products.html', context)


def productdetail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'product' : product,
    }
    return render(request, 'ecommerce/single-product.html', context)

def pay(request, pk):
    product = get_object_or_404(Product, pk=pk)
    context = {
        'product': product,
    }
    return render(request, 'ecommerce/confirm.html', context)


def confirm(request, pk):
    product = get_object_or_404(Product, pk=pk)
    price = product.price
    if request.method == 'POST':
        try:
            phonenumber = request.POST.get('phonenumber')
            userdetail = get_object_or_404(UserDetail, phonenumber=phonenumber)
        except:
            messages.error(request,"Ensure you fill your phone number and form appropriately.")
        pin = request.POST.get('pin')
        cardnum = request.POST.get('card_number')
        cvv = request.POST.get('card_code')
        expirationmonth = request.POST.get('expmonth')
        expirationyear = request.POST.get('expyear')
        emailaddress = request.POST.get('email')
        name = request.POST.get('name')
        zipcode = request.POST.get('zip_code')
        address = request.POST.get('address')
        city = request.POST.get('city')
        state = request.POST.get('state')
        useraddress = address + city + state
        
        print(type(userdetail.maximumtransaction))
        print(type(userdetail.minimumtransaction))
        print(type(product.price))
        
        if userdetail.maximumtransaction < product.price:
            msg = "Sorry, Transaction not possible. Fraudulent status is more than average.(System detected inconsistent transaction amount)"
            return render(request, 'ecommerce/machine.html', {'msg':msg})
        elif userdetail.minimumtransaction > product.price:
            msgs = "Sorry, Transaction not possible. Fraudulent status is more than average. (System detected inconsistent transaction amount)"
            return render(request, 'ecommerce/machine.html', {'msgs':msgs})
        elif userdetail.password1 != pin:
            msgx = "Sorry, Transaction not possible. Fraudulent status is more than average. (System detected pin mismatch)"
            return render(request, 'ecommerce/machine.html', {'msgx':msgx})      
        
        elif userdetail.cardnumber != cardnum:
            msgs = "Sorry, Transaction not possible. Fraudulent status is more than average. (System detected inconsistent card number)"
            return render(request, 'ecommerce/machine.html', {'msgs':msgs})
        elif userdetail.expirymonth != expirationmonth:
            msgx = "Sorry, Transaction not possible. Fraudulent status is more than average. (System detected inconsistent expiration month)"
            return render(request, 'ecommerce/machine.html', {'msgx':msgx})     
        elif userdetail.expiryyear < expirationyear:
            msgs = "Sorry, Transaction not possible. Fraudulent status is more than average. (System detected inconsistent expiration year)"
            return render(request, 'ecommerce/machine.html', {'msgs':msgs})
        elif userdetail.emailaddress != emailaddress:
            msgx = "Sorry, Transaction not possible. Fraudulent status is more than average. (System detected inconsistent email address)"
            return render(request, 'ecommerce/machine.html', {'msgx':msgx})            
        # elif (userdetail.firstname + userdetail.lastname) not in name:
        #     msgs = "Sorry, Transaction not possible. Fraudulent status is more than average. (System detected inconsistent name)"
        #     return render(request, 'ecommerce/machine.html', {'msgs':msgs})
        elif userdetail.zipcode != zipcode:
            msgx = "Sorry, Transaction not possible. Fraudulent status is more than average. (System detected inconsistent zip code)"
            return render(request, 'ecommerce/machine.html', {'msgx':msgx})         
        elif userdetail.address not in useraddress:
            msgx = "Sorry, Transaction not possible. Fraudulent status is more than average. (System detected inconsistent user address)"
            return render(request, 'ecommerce/machine.html', {'msgx':msgx})       
          
        else:
            norm = "Success"
            return render(request, 'ecommerce/machine.html',{'norm':norm})
    context = {
        'price':price,
    }
    return render(request, 'ecommerce/machine.html',context)

ecommerce/templates/ecommerce/machine.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Machine System</title>
</head>
<style>
/* Center the loader */
#loader {
  position: absolute;
  left: 50%;
  top: 50%;
  z-index: 1;
  width: 120px;
  height: 120px;
  margin: -76px 0 0 -76px;
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #3498db;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

/* Add animation to "page content" */
.animate-bottom {
  position: relative;
  -webkit-animation-name: animatebottom;
  -webkit-animation-duration: 1s;
  animation-name: animatebottom;
  animation-duration: 1s
}

@-webkit-keyframes animatebottom {
  from { bottom:-100px; opacity:0 } 
  to { bottom:0px; opacity:1 }
}

@keyframes animatebottom { 
  from{ bottom:-100px; opacity:0 } 
  to{ bottom:0; opacity:1 }
}

#myDiv {
  display: none;
  text-align: center;
}
</style>
<body style="padding:0;margin:0;"  onload="myFunction()">
    {% if messages %}
    {% for message in messages %}
    <script>alert('{{message}}')</script>
    {% endfor %}
    {% endif %}





<div id="loader"></div>

<div style="display:none;" id="myDiv" class="animate-bottom">
  <h1>Artificial Intelligence System</h1>
  <h2>Machine Detection Output..</h2>

  <img src="{% static 'assets/images/robot.jpg' %}" style="width:50%;height:50%;border-radius:10px;">
  <h1>Fraud Probability: </h1>
    {% if msg %}
    <h1 style="color:red;">{{msg}}</h1>
    {% elif msgs %}
    <h1 style="color:red;">{{msgs}}</h1>
    {% elif msgx %}
    <h1 style="color:red;">{{msgx}}</h1>
    {% else %}
    <h3 style="color:green;">No fraud detected.</h3>
    {% endif %}
</div>

<script>
var myVar;

function myFunction() {
  myVar = setTimeout(showPage, 3000);
}

function showPage() {
  document.getElementById("loader").style.display = "none";
  document.getElementById("myDiv").style.display = "block";
}
</script>
</body>
</html>

ecommerce/templates/ecommerce/products.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">

    <title>Ecommerce - Products</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tooplate-main.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
<!--
Tooplate 2114 Pixie
https://www.tooplate.com/view/2114-pixie
-->
  </head>

  <body>
    
    <!-- Pre Header -->
    <!-- <div id="pre-header">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <span>Suspendisse laoreet magna vel diam lobortis imperdiet</span>
          </div>
        </div>
      </div>
    </div> -->

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="#"><img src="{% static 'assets/images/header-logo.png' %}" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <!-- <li class="nav-item">
              <a class="nav-link" href="index.html">Home</a>
            </li> -->
            <li class="nav-item active">
              <a class="nav-link" href="products.html">Products
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="about.html">About Us</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="contact.html">Contact Us</a>
            </li> -->
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <!-- Items Starts Here -->
    <div class="featured-page">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Products</h1>
            </div>
          </div>
          <div class="col-md-8 col-sm-12">
            <!-- <div id="filters" class="button-group">
              <button class="btn btn-primary" data-filter="*">All Products</button>
              <button class="btn btn-primary" data-filter=".new">Newest</button>
              <button class="btn btn-primary" data-filter=".low">Low Price</button>
              <button class="btn btn-primary" data-filter=".high">Hight Price</button>
            </div> -->
          </div>
        </div>
      </div>
    </div>
  
    <div class="featured container no-gutter">

        <div class="row posts">
          {% for product in products %}
            <div id="1" class="item new col-md-4">
              <a href="{% url 'ecommerce:productdetail' pk=product.pk %}">
                <div class="featured-item">
                  <img src="{{ product.image1.url }}" alt="">
                  <h4>{{ product.name }}</h4>
                  <h6>${{ product.price }}</h6>
                </div>
              </a>
            </div>
            {% endfor %}
            <!-- <div id="2" class="item high col-md-4">
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/product-02.jpg" alt="">
                  <h4>Erat odio rhoncus</h4>
                  <h6>$25.00</h6>
                </div>
              </a>
            </div>
            <div id="3" class="item low col-md-4">
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/product-03.jpg" alt="">
                  <h4>Integer vel turpis</h4>
                  <h6>$35.00</h6>
                </div>
              </a>
            </div>
            <div id="4" class="item low col-md-4">
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/product-04.jpg" alt="">
                  <h4>Sed purus quam</h4>
                  <h6>$45.00</h6>
                </div>
              </a>
            </div>
            <div id="5" class="item new high col-md-4">
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/product-05.jpg" alt="">
                  <h4>Morbi aliquet</h4>
                  <h6>$55.00</h6>
                </div>
              </a>
            </div>
            <div id="6" class="item new col-md-4">
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/product-06.jpg" alt="">
                  <h4>Urna ac diam</h4>
                  <h6>$65.00</h6>
                </div>
              </a>
            </div>
            <div id="7" class="item new high col-md-4">
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/product-03.jpg" alt="">
                  <h4>Proin eget imperdiet</h4>
                  <h6>$75.00</h6>
                </div>
              </a>
            </div>
            <div id="8" class="item low new col-md-4">
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/product-02.jpg" alt="">
                  <h4>Nullam risus nisl</h4>
                  <h6>$85.00</h6>
                </div>
              </a>
            </div>
            <div id="9" class="item new col-md-4">
              <a href="single-product.html">
                <div class="featured-item">
                  <img src="assets/images/product-01.jpg" alt="">
                  <h4>Cras tempus</h4>
                  <h6>$95.00</h6>
                </div>
              </a>
            </div> -->
        </div>
    </div>

    <!-- <div class="page-navigation">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul>
              <li class="current-page"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div> -->
    <!-- Featred Page Ends Here -->


    <!-- Subscribe Form Starts Here -->
 
    <!-- Subscribe Form Ends Here -->


    
    <!-- Footer Starts Here -->
    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="logo">
              <img src="{% static 'assets/images/header-logo.png' %}" alt="">
            </div>
          </div>
          <div class="col-md-12">
            <!-- <div class="footer-menu">
              <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">How It Works ?</a></li>
                <li><a href="#">Contact Us</a></li>
              </ul>
            </div> -->
          </div>
          <!-- <div class="col-md-12">
            <div class="social-icons">
              <ul>
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa fa-rss"></i></a></li>
              </ul>
            </div>
          </div> -->
        </div>
      </div>
    </div>
    <!-- Footer Ends Here -->


    <!-- Sub Footer Starts Here -->
    <div class="sub-footer">
      <div class="container">
        <div class="row">
          <!-- <div class="col-md-12">
            <div class="copyright-text">
              <p>Copyright &copy; 2019 Company Name 
                
                - Design: <a rel="nofollow" href="https://www.facebook.com/tooplate">Tooplate</a></p>
            </div>
          </div> -->
        </div>
      </div>
    </div>
    <!-- Sub Footer Ends Here -->


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


    <!-- Additional Scripts -->
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/owl.js' %}"></script>
    <script src="{% static 'assets/js/isotope.js' %}"></script>


    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>


  </body>

</html>

ecommerce/templates/ecommerce/single-product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">

    <title>Ecommerce - Product Detail</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tooplate-main.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flex-slider.css' %}">
<!--
Tooplate 2114 Pixie
https://www.tooplate.com/view/2114-pixie
-->
  </head>

  <body>
    
    <!-- Pre Header -->

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="#"><img src="{% static 'assets/images/header-logo.png' %}" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'ecommerce:allproducts' %}">Products
                <span class="sr-only">(current)</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <!-- Single Starts Here -->
    <div class="single-product">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-heading">
              <div class="line-dec"></div>
              <h1>Single Product</h1>
            </div>
          </div>
          <div class="col-md-6">
            <div class="product-slider">
              <div id="slider" class="flexslider">
                <ul class="slides">
                  <li>
                    <img src="{{ product.image1.url }}" />
                  </li>
                  <li>
                    <img src="{{ product.image1.url }}" />
                  </li>
                  <li>
                    <img src="{{ product.image1.url }}" />
                  </li>
                  <li>
                    <img src="{{ product.image1.url }}" />
                  </li>
                  <!-- items mirrored twice, total of 12 -->
                </ul>
              </div>
              <div id="carousel" class="flexslider">
                <ul class="slides">
                  <li>
                    <img src="{{ product.image1.url }}" />
                  </li>
                  <li>
                    <img src="{{ product.image1.url }}" />
                  </li>
                  <li>
                    <img src="{{ product.image1.url }}" />
                  </li>
                  <li>
                    <img src="{{ product.image1.url }}" />
                  </li>
                  <!-- items mirrored twice, total of 12 -->
                </ul>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="right-content">
              <h4>{{ product.name }}</h4>
              <h6>${{ product.price }}</h6>
              <p>{{ product.description }} </p>
              <!-- <span>7 left on stock</span> -->
              <form action="{% url 'ecommerce:pay' product.pk %}" method="get">
                
                <!-- <label for="quantity">Quantity:</label> -->
                <!-- <input name="quantity" type="quantity" class="quantity-text" id="quantity" 
                	onfocus="if(this.value == '1') { this.value = ''; }" 
                    onBlur="if(this.value == '') { this.value = '1';}"
                    value="1"> -->
                <input type="submit" class="button" value="Order Now!">
              </form>
              <div class="down-content">
                <div class="categories">
                  <!-- <h6>Category: <span><a href="#">Pants</a>,<a href="#">Women</a>,<a href="#">Lifestyle</a></span></h6> -->
                </div>
                <div class="share">
                  <!-- <h6>Share: <span><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-twitter"></i></a></span></h6> -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Single Page Ends Here -->


    <!-- Similar Starts Here -->

    <!-- Similar Ends Here -->


    <!-- Subscribe Form Starts Here -->

    <!-- Subscribe Form Ends Here -->


    
    <!-- Footer Starts Here -->

    <!-- Footer Ends Here -->


    <!-- Sub Footer Starts Here -->
    <div class="sub-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="copyright-text">
              <p>Copyright &copy; 2023 
                
                </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Sub Footer Ends Here -->


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


    <!-- Additional Scripts -->
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/owl.js' %}"></script>
    <script src="{% static 'assets/js/isotope.js' %}"></script>
    <script src="{% static 'assets/js/flex-slider.js' %}"></script>


    <script language = "text/Javascript"> 
      cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
      function clearField(t){                   //declaring the array outside of the
      if(! cleared[t.id]){                      // function makes it static and global
          cleared[t.id] = 1;  // you could use true and false, but that's more typing
          t.value='';         // with more chance of typos
          t.style.color='#fff';
          }
      }
    </script>


  </body>

</html>